### ISSUE TITLE
Bug: "ActionOpenDocumentTree" shows empty items

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [android/storage-samples#17] opened 2019-09-07 23:25 UTC
See:

![image](https://user-images.githubusercontent.com/5357526/64481203-ea47d880-d1df-11e9-8b1a-87a7e63b04eb.png)

**Comment by nic0lette** [comment] 2019-09-09 17:14
Interesting. I suppose those documents don't have names/mime types? (I'm not sure how to reproduce it to see what's going on exactly.)

Do you know what they are?

**Comment by AndroidDeveloperLB** [comment] 2019-09-09 18:26
Why would that matter?
The files have names. The mimetype is an extra data.
The names can't be empty.
You show empty cells.

As for what those are, one is a folder named "gif". One is a folder named "animated webp". Folders !!!
Not only that, but the app shows 2 items with the exact same name, and both don't even exist : "New Folder". On a normal file manager app, and by connecting the PC via USB, I don't see those folders. And, the "files" app also shows them even though they don't exist.
The sample app shows 22 files&folders in total. There are actually only 16 files&folders on the "Download" folder. I tried to restart the OS, and I still see this bug. Trying to press on the empty items shows a toast "No activity found to open null".
A huge bug on Android Q, I think. Android still can't handle files correctly, especially with SAF.
And this is just for existence of files&folders, which is the most basic thing when querying the file system.  When it comes to actually reading and writing from them, it becomes much worse.

The whole SAF API is one big mess. It has all the kinds of disadvantages I can think of: slow, non-standard, no compatibility, no support for third party libraries, breaks apps, non-intuitive for both users and developers, doesn't really provide access to files via file-path, fails to provide the same functionality as File API, no monitoring of files, no full framework support (some framework functions still require file-path alone), no way to grant access to the whole file system...

Really, Android is on the tenth year, and instead of making File API better, it got worse and we are forced to use SAF.
How could it be? Why would Google be a part of such a terrible decision?

**Comment by nic0lette** [comment] 2019-09-26 19:58
I'm sorry, but I'm not able to reproduce the problem, and so I'm not quite sure how to address it. (Either in the sample or providing a use case to the team to identify a bug in the SAF itself)

What device/OS version was this observed on? Does the "Files" app show this directory correctly?

**Comment by AndroidDeveloperLB** [comment] 2019-09-26 22:20
Pixel 2 Q.
OPA1A.190711.020.
As for "Files" app, it doesn't show empty names, but it seems to ignore the folders that I've mentioned ("gif" folder for example doesn't get shown at all).

Why would SAF fail to show a simple folder?
Here, the 2 folders of "gif" and "animated webp", if you really want them:
https://ufile.io/zt35l83j
https://ufile.io/j8g3whn3


Guys please don't force SAF on developers. See how badly it's implemented?
It can't identify folders that my own PC can (connected via USB)...
Even "Files" app, which is a system app (A system app!) can't handle it well, showing only some of the files.

Here, bug report file if you want it too:
https://ufile.io/1rxpw8wv

According to the whole experience I got from how Google handles SAF since it started with Q first preview, nothing that I ever wrote them has succeeded convincing them it's bad and should not be a replacement for files API. Doesn't matter how many bugs, doesn't many how many flaws, doesn't matter how much it's not backward compatible, doesn't matter how it's not supporting libraries, linux commands and even Android's own framework, doesn't matter its performance, doesn't matter the boilerplate code used for it, doesn't matter duplicate code to handle both it and Files API, doesn't matter the bad UX and multiple steps, doesn't matter lack of support by adb, doesn't matter lack of API functions that we have on File API, ...

Doesn't matter anything.
I'm really disappointed.

**Comment by AndroidDeveloperLB** [comment] 2019-09-26 23:38
Here, opened a new bug report:
https://issuetracker.google.com/issues/141672530

And my guess, looking at all of the issues and requests I've made: It will be closed with the comment that either it's too old, not reproducible, or "working as intended" with some weird excuse that doesn't make any sense.

**Comment by nic0lette** [comment] 2019-11-28 00:26
Thank you. Since this seems to be a bug in the platform, rather than this sample, I'm going to close this issue.

**Closed by nic0lette** 2019-11-28 00:26 UTC

**Comment by AndroidDeveloperLB** [comment] 2019-11-28 17:35
Issue still exists though.
